output_dir: output/test-2024-05-22-21-30
llm_params:
  - gpt-4-turbo-preview:
      temperature: 0.7
      max_tokens: 100
  - gpt-3.5-turbo-0125:
      temperature: 0.7

N: 1
num_workers: 5
printout_limit: 50